import java.util.HashMap;

/* Generated By:JJTree: Do not edit this line. ASTAttributionHead.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAttributionHead extends SimpleNode {

  String name = "";

  public ASTAttributionHead(int id) {
    super(id);
  }

  public ASTAttributionHead(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    for (String key : SymbolTable.localVariablesTable.keySet()) {
      HashMap<String, Symbol> templocalVariablesTable = SymbolTable.localVariablesTable.get(key);
      for (String keyb : templocalVariablesTable.keySet()) {
        if (templocalVariablesTable.get(name) == null)
          break;
        if (templocalVariablesTable.get(name).name.equals(name)) {
          return templocalVariablesTable.get(name).getType();
        }
      }
    }

    for (String keyb : SymbolTable.classVariablesTable.keySet()) {
      if (SymbolTable.classVariablesTable.get(name) == null)
        break;
      if (SymbolTable.classVariablesTable.get(name).name.equals(name)) {
        return SymbolTable.classVariablesTable.get(name).getType();
      }
    }

    for (String key : SymbolTable.parametersTable.keySet()) {
      HashMap<String, Symbol> tempparametersTable = SymbolTable.parametersTable.get(key);
      for (String keyb : tempparametersTable.keySet()) {
        if (tempparametersTable.get(name) == null)
          break;
        if (tempparametersTable.get(name).name.equals(name)) {
          return tempparametersTable.get(name).getType();
        }
      }
    }
    throw new SemanticException("Variable \"" + name + "\" not defined.");
  }

  public String toString() {
    return name;
  }

}
/*
 * JavaCC - OriginalChecksum=0816c3b9662b5d5ddfb159dbac17077b (do not edit this
 * line)
 */
