/* Generated By:JJTree: Do not edit this line. ASTArgOperation.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgOperation extends SimpleNode {
  public ASTArgOperation(int id) {
    super(id);
  }

  public ASTArgOperation(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0f02acc4b77ca61aac46cf9f791ef77 (do not edit this line) */
