/* Generated By:JJTree: Do not edit this line. ASTAttribution.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAttribution extends SimpleNode {
  public ASTAttribution(int id) {
    super(id);
  }

  public ASTAttribution(Javamm p, int id) {
    super(p, id);
  }

  public void semanticAnalysis() throws SemanticException {

    SimpleNode first = (SimpleNode) jjtGetChild(0);
    SimpleNode second = (SimpleNode) jjtGetChild(1);

    while (second.getType() == "") {
      if (second.jjtGetNumChildren() == 0)
        break;
      second = (SimpleNode) second.jjtGetChild(0);
    }
    if (!first.getType().equals(second.getType())) {
      throw new SemanticException("The variables <" + first + "> and <" + second + "> should have the same type.");
    }
  }

  public String toString() {
    return "=";
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }
}
/*
 * JavaCC - OriginalChecksum=f9c3d832084598fdc409e50bbc4c21c9 (do not edit this
 * line)
 */
