/* Generated By:JJTree: Do not edit this line. ASTArithm.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArithm extends SimpleNode {

  public String operator = "";

  public ASTArithm(int id) {
    super(id);
  }

  public ASTArithm(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

}
/*
 * JavaCC - OriginalChecksum=bb217ef2c2cae4f3d10ecd5110f31c99 (do not edit this
 * line)
 */
