/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArgument extends SimpleNode {

  public String type = "", name = "";

  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {
    return name;
  }
}
/*
 * JavaCC - OriginalChecksum=92079df33e1d6ba961254bd045197e7d (do not edit this
 * line)
 */
