/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {
    return "argts:";
  }

}
/*
 * JavaCC - OriginalChecksum=d67c971d75841e97021e52b0f49c78be (do not edit this
 * line)
 */
