/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "int";
  }

  public void otherSemanticAnalysis() throws SemanticException {
    SimpleNode first = (SimpleNode) jjtGetChild(0);
    SimpleNode second = (SimpleNode) jjtGetChild(1);
    while (first.getType() == "") {
      first = (SimpleNode) first.jjtGetChild(0);
    }
    while (second.getType() == "") {
      second = (SimpleNode) second.jjtGetChild(0);
    }
    if ((!first.getType().equals("int")) || (!second.getType().equals("int"))) {
      throw new SemanticException("You have to add 2 integers.");
    }
  }

  public String toString() {
    return "+";
  }
}
/*
 * JavaCC - OriginalChecksum=d06d0d2308dcdee8b50c2b3d2ce6c399 (do not edit this
 * line)
 */
