/* Generated By:JJTree: Do not edit this line. ASTArgumentFunctionCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTArgumentFunctionCall extends SimpleNode {

  public String function = "", module = "";

  public ASTArgumentFunctionCall(int id) {
    super(id);
  }

  public ASTArgumentFunctionCall(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {
    return function + "." + module;
  }
}
/*
 * JavaCC - OriginalChecksum=2e1f000f1ae628124a64dd51e79b61a0 (do not edit this
 * line)
 */
