/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(Javamm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "&&";
  }

  @Override
  public String getType() throws SemanticException {
    return "boolean";
  }
}
/*
 * JavaCC - OriginalChecksum=16400d6115db11bc7b3b962817398fb5 (do not edit this
 * line)
 */
