/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTClassDeclaration extends SimpleNode {

  String className = "", extension = "";

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {
    return "class " + this.className + " " + this.extension;
  }
}
/*
 * JavaCC - OriginalChecksum=f2cc1c5f4dadf5d2d38aee5698a1f372 (do not edit this
 * line)
 */
