/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTDiv extends SimpleNode {
  public ASTDiv(int id) {
    super(id);
  }

  public ASTDiv(Javamm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "/";
  }

  @Override
  public String getType() throws SemanticException {
    return "int";
  }

  public void semanticAnalysis() throws SemanticException {
    SimpleNode first = (SimpleNode) jjtGetChild(0);
    SimpleNode second = (SimpleNode) jjtGetChild(1);
    while (first.getType() == "") {
      first = (SimpleNode) first.jjtGetChild(0);
    }
    while (second.getType() == "") {
      second = (SimpleNode) second.jjtGetChild(0);
    }
    if ((!first.getType().equals("int")) || (!second.getType().equals("int"))) {
      throw new SemanticException("You must divide 2 integers.");
    }
  }

}
/*
 * JavaCC - OriginalChecksum=c23d411ff5070211f3dd9888e11456b2 (do not edit this
 * line)
 */
