/* Generated By:JJTree: Do not edit this line. ASTExpressionCmp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionCmp extends SimpleNode {

  public String operator = "";

  public ASTExpressionCmp(int id) {
    super(id);
  }

  public ASTExpressionCmp(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

}
/*
 * JavaCC - OriginalChecksum=1c6845371a0c4d1d55b99c21d7a6815b (do not edit this
 * line)
 */
