/* Generated By:JJTree: Do not edit this line. ASTExclamationMark.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExclamationMark extends SimpleNode {
  public ASTExclamationMark(int id) {
    super(id);
  }

  public ASTExclamationMark(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "boolean";
  }

}
/*
 * JavaCC - OriginalChecksum=ce0d3e2c102acb11f99d90b3350551cd (do not edit this
 * line)
 */
