/* Generated By:JJTree: Do not edit this line. ASTExpressionArray.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionArray extends SimpleNode {
  public ASTExpressionArray(int id) {
    super(id);
  }

  public ASTExpressionArray(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  @Override
  public String toString() {
    return "Array";
  }

}
/*
 * JavaCC - OriginalChecksum=b71de507401ef2565b4985fdefad161b (do not edit this
 * line)
 */
