/* Generated By:JJTree: Do not edit this line. ASTerror_skip_while.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTerror_skip_while extends SimpleNode {
  public ASTerror_skip_while(int id) {
    super(id);
  }

  public ASTerror_skip_while(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }
}
/*
 * JavaCC - OriginalChecksum=4f47ac6b95dc0cc80c5667267b008ecc (do not edit this
 * line)
 */
