/* Generated By:JJTree: Do not edit this line. ASTExpressionMethod.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionMethod extends SimpleNode {

  public String module = "";

  public ASTExpressionMethod(int id) {
    super(id);
  }

  public ASTExpressionMethod(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

}
/*
 * JavaCC - OriginalChecksum=2ce98b438c5bb73127c18f1de9ed197d (do not edit this
 * line)
 */
