/* Generated By:JJTree: Do not edit this line. ASTExpressionMult.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTExpressionMult extends SimpleNode {

  public String operator = "";

  public ASTExpressionMult(int id) {
    super(id);
  }

  public ASTExpressionMult(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

}
/*
 * JavaCC - OriginalChecksum=11fb70b0ce8bce7913bd25ecdf5e0c68 (do not edit this
 * line)
 */
