/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTFunctionCall extends SimpleNode {

  public String function = "", module = "";

  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  @Override
  public String toString() {
    return function + "." + module;
  }

}
/*
 * JavaCC - OriginalChecksum=63f8a79ee3624dfeb7ccf2ab1acef33b (do not edit this
 * line)
 */
