/* Generated By:JJTree: Do not edit this line. ASTLess.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTLess extends SimpleNode {
  public ASTLess(int id) {
    super(id);
  }

  public ASTLess(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "boolean";
  }

  public String toString() {
    return "<";
  }

}
/*
 * JavaCC - OriginalChecksum=4e0e4539c3f45fb6ea892667cc7a8efd (do not edit this
 * line)
 */
