/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMethodDeclaration extends SimpleNode {

  public String methodName = "", methtodReturn = "";

  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {
    return methodName;
  }

  public String getMethodName() {
    return methodName;
  }

}
/*
 * JavaCC - OriginalChecksum=2edfd2c42f0d0efd8da3bea1df21c88b (do not edit this
 * line)
 */
