/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTModule extends SimpleNode {

  public String name = "";

  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

}
/*
 * JavaCC - OriginalChecksum=71391f7b28e80bdb2d39aed074c253b7 (do not edit this
 * line)
 */
