/* Generated By:JJTree: Do not edit this line. ASTMethodArguments.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMethodArguments extends SimpleNode {

  public String identifier = "", type = "";

  public ASTMethodArguments(int id) {
    super(id);
  }

  public ASTMethodArguments(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String getMethodArgumentName() {
    return identifier;
  }

  public String getMethodArgumentType() {
    return type;
  }

  public String toString() {
    return "Argument (" + this.identifier + ")";
  }

}
/*
 * JavaCC - OriginalChecksum=f7c4aa63104cf41accc2eb02a31485d6 (do not edit this
 * line)
 */
