/* Generated By:JJTree: Do not edit this line. ASTMethods.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTMethods extends SimpleNode {

  String module = "";

  public ASTMethods(int id) {
    super(id);
  }

  public ASTMethods(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  @Override
  public String toString() {
    return "Method " + module;
  }

}
/*
 * JavaCC - OriginalChecksum=2098f4974239e944061b174918753a3a (do not edit this
 * line)
 */
