/* Generated By:JJTree: Do not edit this line. ASTNewArgumentFunctionCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTNewArgumentFunctionCall extends SimpleNode {

  public String function = "", module = "";

  public ASTNewArgumentFunctionCall(int id) {
    super(id);
  }

  public ASTNewArgumentFunctionCall(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  @Override
  public String toString() {
    return function + "." + module;
  }
}
/*
 * JavaCC - OriginalChecksum=596ec738d17f851992b73bb471fd4bf6 (do not edit this
 * line)
 */
