/* Generated By:JJTree: Do not edit this line. ASTNewDeclarations.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTNewDeclarations extends SimpleNode {

  public String name = "";

  public ASTNewDeclarations(int id) {
    super(id);
  }

  public ASTNewDeclarations(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  @Override
  public String toString() {
    return name;
  }
}
/*
 * JavaCC - OriginalChecksum=4ed5e1caadf3938677e2553412e294ea (do not edit this
 * line)
 */
