/* Generated By:JJTree: Do not edit this line. ASTParenthesisArithm.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParenthesisArithm extends SimpleNode {
  public ASTParenthesisArithm(int id) {
    super(id);
  }

  public ASTParenthesisArithm(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d95f6a49f9e701aab9c0d61ab9a96512 (do not edit this line) */
