/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTReturn extends SimpleNode {

  public String identifier = "";
  public Integer val = null;

  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

}
/*
 * JavaCC - OriginalChecksum=5f6165d503b6bfa97462193c9f1f4afa (do not edit this
 * line)
 */
