/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTStatement extends SimpleNode {

  public String name = "";

  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {

    if (name != "") {
      return name;
    } else
      return JavammTreeConstants.jjtNodeName[id];
  }

}
/*
 * JavaCC - OriginalChecksum=4711b25b6c827dac146e6b74e2311577 (do not edit this
 * line)
 */
