/* Generated By:JJTree: Do not edit this line. ASTStatementIf.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTStatementIf extends SimpleNode {
  public ASTStatementIf(int id) {
    super(id);
  }

  public ASTStatementIf(Javamm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Statement (If)";
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }
}
/*
 * JavaCC - OriginalChecksum=8522d4b49f081aee252ed2eae944c422 (do not edit this
 * line)
 */
