/* Generated By:JJTree: Do not edit this line. ASTSub.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTSub extends SimpleNode {
  public ASTSub(int id) {
    super(id);
  }

  public ASTSub(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "int";
  }

  @Override
  public String toString() {
    return "-";
  }

  public void semanticAnalysis() throws SemanticException {
    SimpleNode first = (SimpleNode) jjtGetChild(0);
    SimpleNode second = (SimpleNode) jjtGetChild(1);

    while (first.jjtGetNumChildren() != 0) {
      first = (SimpleNode) first.jjtGetChild(0);
    }
    while (second.jjtGetNumChildren() != 0) {
      second = (SimpleNode) second.jjtGetChild(0);
    }
    if ((!first.getType().equals("int")) || (!second.getType().equals("int"))) {
      throw new SemanticException("You must subtract 2 integers.");
    }
  }

}
/*
 * JavaCC - OriginalChecksum=d28b5fe64f7ba93518ba51451686cb39 (do not edit this
 * line)
 */
