/* Generated By:JJTree: Do not edit this line. ASTType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTType extends SimpleNode {

  public String type = "";
  public Boolean isArray = false;

  public ASTType(int id) {
    super(id);
  }

  public ASTType(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {
    if (isArray)
      type = type + "[]";
    return type;
  }

}
/*
 * JavaCC - OriginalChecksum=58f966ae430c9095b01019da25de4f81 (do not edit this
 * line)
 */
