/* Generated By:JJTree: Do not edit this line. ASTThisFunctionCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThisFunctionCall extends SimpleNode {
  public ASTThisFunctionCall(int id) {
    super(id);
  }

  public ASTThisFunctionCall(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f7dae91a912d07e42c92db54cc51321b (do not edit this line) */
