/* Generated By:JJTree: Do not edit this line. ASTThisCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTThisCall extends SimpleNode {

  public String function = "this", module = "";

  public ASTThisCall(int id) {
    super(id);
  }

  public ASTThisCall(Javamm p, int id) {
    super(p, id);
  }

  public String toString() {
    if (module != "")
      return "this." + module;
    return "this.";
  }

}
/*
 * JavaCC - OriginalChecksum=4e1e64d704ff2253aba933258372212a (do not edit this
 * line)
 */
