/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTVarDeclaration extends SimpleNode {

  String varName = "";

  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String getType() throws SemanticException {
    return "";
  }

  public String toString() {
    return varName;
  }

  public String getVarName() {
    return varName;
  }

}
/*
 * JavaCC - OriginalChecksum=4a00f9ba270fbc9886aa0ccdf9c733e8 (do not edit this
 * line)
 */
