/* Generated By:JJTree&JavaCC: Do not edit this line. JavammConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavammConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEW = 1;
  /** RegularExpression Id. */
  int WHILE = 2;
  /** RegularExpression Id. */
  int IF = 3;
  /** RegularExpression Id. */
  int ELSE = 4;
  /** RegularExpression Id. */
  int THIS = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int FALSE = 8;
  /** RegularExpression Id. */
  int CLASS = 9;
  /** RegularExpression Id. */
  int PUBLIC = 10;
  /** RegularExpression Id. */
  int LENGTH = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int BOOLEAN = 13;
  /** RegularExpression Id. */
  int EXTENDS = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int MAIN = 16;
  /** RegularExpression Id. */
  int STATIC = 17;
  /** RegularExpression Id. */
  int STRINGLIT = 18;
  /** RegularExpression Id. */
  int SLASH = 19;
  /** RegularExpression Id. */
  int LPAR = 20;
  /** RegularExpression Id. */
  int RPAR = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int LBRACE = 24;
  /** RegularExpression Id. */
  int RBRACE = 25;
  /** RegularExpression Id. */
  int RECTBRACEL = 26;
  /** RegularExpression Id. */
  int RECTBRACER = 27;
  /** RegularExpression Id. */
  int DOT = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int MULT = 31;
  /** RegularExpression Id. */
  int DIV = 32;
  /** RegularExpression Id. */
  int LESS = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int ASSIGN = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;
  /** RegularExpression Id. */
  int LETTER = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 45;
  /** RegularExpression Id. */
  int STRING = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"new\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"this\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"class\"",
    "\"public\"",
    "\"length\"",
    "\"return\"",
    "\"boolean\"",
    "\"extends\"",
    "\"void\"",
    "\"main\"",
    "\"static\"",
    "\"String\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\"&&\"",
    "\"=\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 40>",
    "<token of kind 41>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGERLITERAL>",
    "<STRING>",
    "\"!\"",
  };

}
