/* Generated By:JavaCC: Do not edit this line. JavammTreeConstants.java Version 7.0.2 */
public interface JavammTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTMETHODARGUMENTS = 5;
  public int JJTMETHODARGUMENTPIECE = 6;
  public int JJTRETURN = 7;
  public int JJTTYPE = 8;
  public int JJTSTATEMENT = 9;
  public int JJTWHILE = 10;
  public int JJTATTRIBUTION = 11;
  public int JJTFUNCTIONCALL = 12;
  public int JJTNEWARGUMENTFUNCTIONCALL = 13;
  public int JJTARGUMENTFUNCTIONCALL = 14;
  public int JJTARGUMENTLIST = 15;
  public int JJTARGUMENT = 16;
  public int JJTARGOPERATION = 17;
  public int JJTVOID = 18;
  public int JJTSTATEMENTIF = 19;
  public int JJTELSE = 20;
  public int JJTATTRIBUTIONHEAD = 21;
  public int JJTEXPRESSION = 22;
  public int JJTTRUE = 23;
  public int JJTFALSE = 24;
  public int JJTNEWDECLARATIONS = 25;
  public int JJTARITHM = 26;
  public int JJTADD = 27;
  public int JJTSUB = 28;
  public int JJTEXPRESSIONMULT = 29;
  public int JJTMULT = 30;
  public int JJTDIV = 31;
  public int JJTEXPRESSIONCMP = 32;
  public int JJTLESS = 33;
  public int JJTAND = 34;
  public int JJTTERM = 35;
  public int JJTTHISCALL = 36;
  public int JJTTHISFUNCTIONCALL = 37;
  public int JJTPARENTHESISARITHM = 38;
  public int JJTEXCLAMATIONMARK = 39;
  public int JJTEXPRESSIONARRAY = 40;
  public int JJTEXPRESSIONMETHOD = 41;
  public int JJTMETHODS = 42;
  public int JJTERROR_SKIPTO = 43;
  public int JJTERROR_SKIP_WHILE = 44;


  public String[] jjtNodeName = {
    "Module",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "MethodArguments",
    "MethodArgumentPiece",
    "Return",
    "Type",
    "Statement",
    "While",
    "Attribution",
    "FunctionCall",
    "NewArgumentFunctionCall",
    "ArgumentFunctionCall",
    "ArgumentList",
    "Argument",
    "ArgOperation",
    "void",
    "StatementIf",
    "Else",
    "AttributionHead",
    "Expression",
    "True",
    "False",
    "NewDeclarations",
    "Arithm",
    "Add",
    "Sub",
    "ExpressionMult",
    "Mult",
    "Div",
    "ExpressionCmp",
    "Less",
    "And",
    "Term",
    "ThisCall",
    "ThisFunctionCall",
    "ParenthesisArithm",
    "ExclamationMark",
    "ExpressionArray",
    "ExpressionMethod",
    "Methods",
    "error_skipto",
    "error_skip_while",
  };
}
/* JavaCC - OriginalChecksum=9a92e08356323b8faa8031e8422e4e1a (do not edit this line) */
